export const routes = {
  home: '/',
  notFound: '*',
  products: '/product',
  itemDetail: '/product/:itemId',
  category: '/category/:categoryId',
  login: '/login',
  register: '/register',
  dashboard: '/administracion/',
  dashboardusers: '/administracion/users',
  dashboardproducts: '/administracion/products',
  dashboardcategories: '/administracion/categories',
  dashboardfeatures: '/administracion/features',
  dashboardorders: '/administracion/orders',
  dashboardsettings: '/administracion/settings',
  search: '/search',
  cart: '/cart',
}
