-- Agrega las categorias
INSERT INTO categories (id, name, image_url, description) VALUES
	 (1, 'Cámaras', 'https://res.cloudinary.com/wilsondelcanto-dev/image/upload/v1717018987/categories/adatfk3bwthx713nbyyc.jpg', 'Camaras de fotos y video.'),
	 (2, 'Sonido', 'https://res.cloudinary.com/wilsondelcanto-dev/image/upload/v1717019008/categories/p4imbfvzytianq3rjsqx.jpg', 'Equipos de sonido.'),
	 (3, 'Luces', 'https://res.cloudinary.com/wilsondelcanto-dev/image/upload/v1717019028/categories/pfoeqmaypxsh45debsju.jpg', 'Luces para eventos.'),
	 (4, 'Accesorios', 'https://res.cloudinary.com/wilsondelcanto-dev/image/upload/v1717018983/categories/l0zanig5xcmuz3crdiex.jpg', 'Accesorios para eventos.');

-- Agrega los productos por defecto
-- INSERT INTO products (
-- 		description,
-- 		images,
-- 		name,
-- 		price,
-- 		stock,
-- 		category_id
-- 	)
-- VALUES (
-- 		'Esta cámara réflex de Canon está muy equilibrada en cuanto a precio y calidad tanto en fotografía como en vídeo. Si no buscas una cámara profesional pero tampoco quieres quedarte corto, la Canon EOS 850D es una opción muy interesante:',
-- 		'https://res.cloudinary.com/wilsondelcanto-dev/image/upload/v1716069818/visual-service/vyz7wauxancpgyttulgf.jpg',
-- 		'Canon E0S 850D',
-- 		832.0,
-- 		1,
-- 		1
-- 	),
-- 	(
-- 		'Esta cámara réflex puede ser una opción interesante si quieres buenos resultados fotográficos a la vez que consigues unas tomas de vídeo en 4K de muy buena calidad incluso en situaciones de poca luz.',
-- 		'https://res.cloudinary.com/wilsondelcanto-dev/image/upload/v1716069990/visual-service/vo5qvbymezheuoaif3id.jpg',
-- 		'NIKON D7500',
-- 		1019.0,
-- 		1,
-- 		1
-- 	),
-- 	(
-- 		'La OM-D E-M10 Mark IV es una cámara sin espejo de Olympus, ideal para viajes, tiene muy buena relación calidad precio y puede ser una opción para adentrarte en el mundo del vídeo con resultados más que aceptables.',
-- 		'https://res.cloudinary.com/wilsondelcanto-dev/image/upload/v1716070123/visual-service/pjc403lk3jksbnfnhjfx.jpg',
-- 		'OLYMPUS OM-D E-M10 MARK IV',
-- 		710.0,
-- 		1,
-- 		1
-- 	),
-- 	(
-- 		'Esta Sony A7 III no es para ti si recién te inicias en vídeo o en fotografía, ni por prestaciones ni por presupuesto. Es una cámara de vídeo para aficionados avanzados o para los que quieran obtener resultados muy profesionales.',
-- 		'https://res.cloudinary.com/wilsondelcanto-dev/image/upload/v1716070189/visual-service/bhyxk97soy4y30syunn9.png',
-- 		'SONY A7 III',
-- 		1189.0,
-- 		1,
-- 		1
-- 	),
-- 	(
-- 		'Con sensor de fotograma completo, excelente visor electrónico, muy buen rango dinámico y autoenfoque con seguimiento de animales y ojo en grabaciones de vídeo, esta Nikon Z6 II tiene mucho que ofrecer a los fotógrafos que también hacen vídeo.',
-- 		'https://res.cloudinary.com/wilsondelcanto-dev/image/upload/v1716070220/visual-service/qop2xzv509imspapoju4.png',
-- 		'NIKON Z6 II',
-- 		2170.0,
-- 		1,
-- 		1
-- 	),
-- 	(
-- 		'Otra cámara EVIL que vale la pena tener en el radar si lo que te gusta es grabar vídeo pero, además, disfrutas haciendo fotografía, es esta sin espejo de Fujifilm. Está pensada para vlogging pero ofrece mucho más en cuanto a vídeo. Lo más destacable es que graba sin recortes con proporción 3:2 y una resolución de 6,2K.',
-- 		'https://res.cloudinary.com/wilsondelcanto-dev/image/upload/v1716070265/visual-service/agryn6vy5hrxul3ie9aq.jpg',
-- 		'FUJIFILM X-S20',
-- 		1361.0,
-- 		1,
-- 		1
-- 	),
-- 	(
-- 		'Sin espejo impresionante para grabar vídeo es la Lumix GH5s. Está concebida precisamente para ello y, si bien no es barata, si puedes permitírtela es una apuesta segura con la que conseguirás resultados espectaculares, además de buena cámara fotográfica',
-- 		'https://res.cloudinary.com/wilsondelcanto-dev/image/upload/v1716070292/visual-service/a4ktavfgc4g0txhnnwl0.jpg',
-- 		'PANASONIC LUMIX GH5S',
-- 		1299.0,
-- 		1,
-- 		1
-- 	),
-- 	(
-- 		'Tengo que confesar que la Nikon Z50 se ha convertido en mi nueva favorita dentro de las cámaras de fotos para aficionados. Por un precio por debajo de los 1000 euros ofrece excelentes prestaciones tanto para fotografía como para vídeo.',
-- 		'https://res.cloudinary.com/wilsondelcanto-dev/image/upload/v1716070328/visual-service/oalwfp8ucfqtsytepvq8.jpg',
-- 		'NIKON Z50',
-- 		867.0,
-- 		1,
-- 		1
-- 	),
-- 	(
-- 		'Esta cámara sin espejo para aficionados avanzados, además de ser bastante compacta y ligera, no solo tiene un precio más que atractivo, sino que es perfecta para pequeñas producciones, vloggers y otros creadores de contenido que quieren hacer tanto fotografía como vídeo.',
-- 		'https://res.cloudinary.com/wilsondelcanto-dev/image/upload/v1716070356/visual-service/z4uwycrc1cge8bj2z2t5.jpg',
-- 		'CANON EOS M6 MARK II',
-- 		1999.0,
-- 		1,
-- 		1
-- 	),
-- 	(
-- 		'Una cámara sin espejo espectacular tanto para fotografía como para vídeo. Puedes ir haciendo una señal al lado de cada una de las características que te recomendé al empezar esta artículo porque tiene todo lo que puedas imaginar.',
-- 		'https://res.cloudinary.com/wilsondelcanto-dev/image/upload/v1716072431/visual-service/pnjpaqenqdk0lr2d0jwo.jpg',
-- 		'OLYMPUS OM-D E-M10 MARK V',
-- 		710.0,
-- 		1,
-- 		1
-- 	),
-- 	(
-- 		'Una cámara sin espejo espectacular tanto para fotografía como para vídeo. Puedes ir haciendo una señal al lado de cada una de las características que te recomendé al empezar esta artículo porque tiene todo lo que puedas imaginar.',
-- 		'https://res.cloudinary.com/wilsondelcanto-dev/image/upload/v1716072513/visual-service/wfuqfzxztpfkusumkeid.jpg',
-- 		'SONY A6600',
-- 		1189,
-- 		1,
-- 		1
-- 	),
-- 	(
-- 		'Increíblemente pequeño - Con un peso de sólo 9 g, el micrófono inalambrico solapa LARK M2 permanecerá firmemente sujeto a su ropa. Con su reproducción de sonido sin pérdidas y sus extraordinarias capacidades de grabación, te ofrece un excelente rendimiento de grabación sin igual.',
-- 		'https://res.cloudinary.com/wilsondelcanto-dev/image/upload/v1716072546/visual-service/ivpgsexz1vykuqdtdh52.jpg',
-- 		'Hollyland Lark M2 Combo',
-- 		199.0,
-- 		1,
-- 		1
-- 	),
-- 	(
-- 		'Hay 3 tipos de accesorios de conexión para micrófono Lavalier inalámbrico FULAIM X5: adaptador de iPhone, adaptador tipo C, cable de audio de cámara de 3,5 mm. El sistema de micrófono Lavalier es ampliamente compatible con iPhone, iPad, Samsung, teléfono Android, cámara, laptop, tableta y computadora. Plug and Play, emparejamiento automático una vez que los enciende. Permite un rango de transmisión de hasta 200 m.',
-- 		'https://res.cloudinary.com/wilsondelcanto-dev/image/upload/v1716072616/visual-service/ywfczur4rdiwhna0fwmw.jpg',
-- 		'FULAIM X5',
-- 		116.0,
-- 		1,
-- 		1
-- 	),
-- 	(
-- 		'BOYALINK viene con un estuche de carga, un pequeño estuche portátil que contiene 1 receptor y 2 transmisores, así como 3 adaptadores (Lightning, Type-C y conectores Jack de 3,5MM). Esto asegura su gran flexibilidad y amplia compatibilidad.',
-- 		'https://res.cloudinary.com/wilsondelcanto-dev/image/upload/v1716072704/visual-service/kejuiwk8fotjsypq6t7z.jpg',
-- 		'BOYALINK',
-- 		109.0,
-- 		1,
-- 		1
-- 	),
-- 	(
-- 		'El VideoMicro II combina un sonido impresionante con un funcionamiento increíblemente sencillo. No necesita pilas, ya que se alimenta por su conexión de 3,5 mm, y no hay interruptores ni controles complicados; basta con conectar el micrófono y pulsar el botón de grabación de la cámara o smartphone para capturar audio profesional.',
-- 		'https://res.cloudinary.com/wilsondelcanto-dev/image/upload/v1716072734/visual-service/q2ghz3gbsuqqzkiri9oa.jpg',
-- 		'RØDE VideoMicro II',
-- 		75.0,
-- 		1,
-- 		1
-- 	),
-- 	(
-- 		'El micrófono condensador de escopeta BY-BM6060 está diseñado para la producción de video y la adquisición de audio de transmisión (ENG/EFP). Ideal para entrevistas, películas independientes, programas de televisión, documentales, videos promocionales y grabaciones de estudio.',
-- 		'https://res.cloudinary.com/wilsondelcanto-dev/image/upload/v1716072763/visual-service/evirzyn006dfs4nhmke3.jpg',
-- 		'XLR de Escopeta BY-BM6060',
-- 		85.0,
-- 		1,
-- 		1
-- 	),
-- 	(
-- 		'Esta luz LED para escenario es perfecta para decoración de interiores y exteriores, decoración de dormitorio, plaza pública, pista de patinaje, suministros de fiesta de cumpleaños, reunión familiar, discoteca, bar, banquete, boda, baile, hotel, karaoke, conciertos y otros lugares de entretenimiento.',
-- 		'https://res.cloudinary.com/wilsondelcanto-dev/image/upload/v1716072793/visual-service/np5jriurotfguchiasji.jpg',
-- 		'Fresnel COB de 200 W',
-- 		132.0,
-- 		1,
-- 		2
-- 	),
-- 	(
-- 		'Con 252 LED blanco cálido, 252 LED blanco frío, 140 LED RGB, esta luz de video LED de 50 W y 644 LED cuenta con una iluminación máxima de 3800 lux/3.3 ft, temperatura de color ajustable de 2300 K ~ 8500 K, modo de 27 colores y brillo ajustable del 0% al 100%.',
-- 		'https://res.cloudinary.com/wilsondelcanto-dev/image/upload/v1716072826/visual-service/z3qqhvxowud6r46mpc3t.jpg',
-- 		'Kit de iluminación ALTSON, 2 luces LED bicolor de 50 W',
-- 		153.0,
-- 		1,
-- 		2
-- 	),
-- 	(
-- 		'Proporciona 3 temperaturas de color (2800 K, 4800 K y 6500 K) para crear varios ambientes de iluminación; esta luz de estudio mejorada está equipada con 352 cuentas LED para hacer que la luz sea más amplia y evitar sombras innecesarias. Cuenta con un alto CRI de 97+ para una reproducción precisa del color. Ajusta el brillo en un rango de 10 a 100% con botón hacia arriba y hacia abajo en el control remoto para satisfacer diferentes circunstancias de fotografía, ofreciendo iluminación adicional para tus trabajos',
-- 		'https://res.cloudinary.com/wilsondelcanto-dev/image/upload/v1716072847/visual-service/k5zmc708jfwz537ecpid.jpg',
-- 		'Kit de iluminación NiceVeedi Studio, 2 luces LED de 2800-6500K',
-- 		50.0,
-- 		1,
-- 		2
-- 	),
-- 	(
-- 		'Nueva tecnología COB luz de escenario: basada en la última tecnología COB (chip on board), las luces de escenario de iglesia emiten alta intensidad, alta uniformidad, haz de luz blanca fría/blanca cálida de mayor calidad con menos consumo de energía en comparación con la antigua tecnología LED, rango efectivo de 19.7 ft, ángulo de haz de 78°.',
-- 		'https://res.cloudinary.com/wilsondelcanto-dev/image/upload/v1716072869/visual-service/bdjyrztlwzrevhnqx8ur.jpg',
-- 		'BETOPPER COB de 200 W',
-- 		103.0,
-- 		1,
-- 		2
-- 	),
-- 	(
-- 		'2 proyectores de luz de video de tungsteno Fresnel de 1000 W + 1 estudio de luz de tungsteno de 650 W. Estas series Fresnel son ideales para su uso donde se requieren focos Fresnel de tungsteno compactos y ligeros. Es la solución perfecta en pequeños estudios donde la altura de la rejilla es un problema. La construcción de aluminio extruido y fundido a presión resistente a la corrosión maximiza la fuerza del cuerpo mientras mantiene el peso ligero de un accesorio de ubicación ideal, a pesar del tamaño pequeño, lentes de longitud focal corta con ángulos más anchos dan más salida de luz y una mejor distribución de la luz en toda el área de bearn. El atenuador se puede instalar en estos artículos',
-- 		'https://res.cloudinary.com/wilsondelcanto-dev/image/upload/v1716072891/visual-service/mzezgszm2zibhylfv4ot.jpg',
-- 		'Came-TV Fresnel de tungsteno, 2 x 1000 W y 1 x 650 W',
-- 		520.0,
-- 		1,
-- 		2
-- 	),
-- 	(
-- 		'Hecho de aleación de aluminio de alta calidad que hace que la estructura sea más estable, duradera, portátil y ligera',
-- 		'https://res.cloudinary.com/wilsondelcanto-dev/image/upload/v1716072916/visual-service/lijloktmye1xpefh1qnb.jpg',
-- 		'Kit EMART, 2 Soporte de luz de 7 pies',
-- 		30.0,
-- 		1,
-- 		3
-- 	),
-- 	(
-- 		'El soporte de luz SmallRig 3736 cuenta con un cojín de aire confiable, que evita eficazmente caídas repentinas y pellizcos de los dedos durante el ajuste de altura. Mejora la seguridad y la estabilidad para la toma de fotos y videos.',
-- 		'https://res.cloudinary.com/wilsondelcanto-dev/image/upload/v1716072941/visual-service/lf2lp73qbvxh1yqqq334.jpg',
-- 		'SMALLRIG RA-S280-3736 Soporte de luz de 110 pulgadas',
-- 		68.0,
-- 		1,
-- 		3
-- 	),
-- 	(
-- 		'Estabilizador de cámara, cardán de mano de 3 ejes para cámaras DSLR y sin espejo, carga útil de hasta 4.4 libras compatible con Sony, Panasonic Lumix, Nikon, Canon. Diseño ligero para la filmación',
-- 		'https://res.cloudinary.com/wilsondelcanto-dev/image/upload/v1716072966/visual-service/x9yqrk4mrhpjvx3hvrqn.jpg',
-- 		'DJI Ronin-SC - Estabilizador de cámara',
-- 		279.0,
-- 		1,
-- 		3
-- 	);


