name: CI

on:
  push:
    branches: [ "front-end" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.13.0'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
